### PR TITLE
Implement dark mode via Bootstrap

### PR DESCRIPTION
**Pull request by patdnr**
*EDIT by Doug:* [Bootstrap 5.3](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/) with first-class support for dark mode was released on May 30.

Cross-project tracking: https://github.com/gaepdit/EPD-IT/issues/117

### CODE REVIEW

**Review by dougwaldron — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

    
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)

**Comment by patdnr** [comment]
The files in the webfonts folder are from https://github.com/icons8/line-awesome. The license allows us to do anything with it (https://github.com/icons8/line-awesome#good-boy-license)

**Comment by patdnr** [comment]
@dougwaldron The icon is from font-awesome (https://astronautweb.co/snippet/font-awesome/), specifically "\f185" and "\f186". I am using the free version, which allows commercial use.

**Comment by patdnr** [comment]
Everything is completed. Waiting for Bootstrap (https://www.nuget.org/packages/bootstrap/absoluteLatest) to exit its alpha version

**Pull request merged**
