### PR TITLE
82 add rich text editor for comments etc

### PR DESCRIPTION
**Pull request by YoyoCaleb**
Added rich text editor. 

Edited Notes for "WorkEntry ID 10000000-0000-0000-0000-000000000000" to show that Markdown is expressed in HTML
image

You can also create your own WorkEntry to test the editor.

image

### CODE REVIEW

**Comment by YoyoCaleb** [comment]
Editor below. There is text overlaying the editor that I am unsure what to do with.
image

**Review by dougwaldron — CHANGES_REQUESTED** [review]
@YoyoCaleb, this is a good start. There are several issues to work on, but I don't see any major obstacles yet. Let me know if you want to meet to go over any of these.

* The output doesn't get formatted in the current PR version. I see you added the Markdig package, but it isn't used anywhere. Did you forget to push a commit?

* Speaking of Markdig, you've added it to all projects in the solution. Only add NuGet packages where they're needed.

* The SimpleMDE project has unfortunately [been abandoned](https://github.com/sparksuite/simplemde-markdown-editor/issues/829), but there are other options. [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) is an updated and current fork of SimpleMDE. Another possibility is [ink-mde](https://github.com/davidmyersdev/ink-mde).

* The CSS you've added doesn't work well with light-mode. Ink-mde advertises that it is compatible with color schemes, though I haven't verified that. For EasyMDE, [this custom CSS](https://github.com/Ionaru/easy-markdown-editor/issues/131#issuecomment-1738202589) might work.

* The overlapping label happens because I used Bootstrap [floating labels](https://getbootstrap.com/docs/5.3/forms/floating-labels/). This can be removed.

* Instead of adding the editor to all textareas, let's make it opt-in with an optional class.

* An HTML page can only have one `<head>` element, so adding one to the ".cshtml" pages is not allowed. The scripts can be added to the `@section Scripts` section at the bottom of the page. Currently I don't have a similar section for the stylesheets but one can be added to the "_Layout" template.

* [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) is important to site security when linking to third-party scripts. (This is why SonarCloud identified 5 [Security hotspots](https://sonarcloud.io/project/security_hotspots?id=gaepdit_template-app&pullRequest=114).) Either host the files locally or add the SRI `integrity` attribute.

I'll put together a code suggestion to illustrate some of these items.

**Comment by dougwaldron** [comment]
Hey @YoyoCaleb, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #114**](https://gitkraken.dev/drafts/09fa9e88-167f-4b10-931f-36ca249401a8?source=PRComment)
>https://github.com/gaepdit/template-app/pull/114

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/09fa9e88-167f-4b10-931f-36ca249401a8?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSDhzYnNNNTBWb1FpIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by YoyoCaleb** [comment]
If possible, I would like to get into a call with you to discuss the changes. Thank you Doug!

**Review by dougwaldron — CHANGES_REQUESTED** [review]
Great progress, Caleb! This is turning out to be a lot more complex than I expected, but we're getting there. Here are some more tasks to work on:

- I'm sure you've heard the phrase, "never trust user input"! There's always a security risk when rendering user-generated content to the browser, and methods like `@Html.Raw()` should raise red flags. Content should be sanitized before being displayed.
    - In the editor: The [EasyMDE docs](https://github.com/Ionaru/easy-markdown-editor) have an example for using a tool called "DOMPurify".
    - On the back end: Sanitize rendered Markdown with [HtmlSanitizer](https://github.com/mganss/HtmlSanitizer). This can be added to your `MarkdownToHtml` method.
- Dark mode is looking good, but the "preview" and "fullscreen" editor modes are still not compatible.
- Add `.UseBootstrap()` to the `MarkdownPipelineBuilder()` to get built-in Bootstrap classes.
- The "Notes" label is below the textarea. Unfortunately, Bootstrap's floating labels feature required the `<label>` to come after the `<textarea>` element. Removing the "form-floating" class requires also moving the label above the textarea. (Ideally, though, the textarea template would use a floating label if MDE is not enabled.)
- Markdig is only used in the WebApp project. So move the "Markdown.cs" file to "src/WebApp/Platform/Rendering" (new folder) and rename the file to "MarkdownHelper.cs" (it should always be the same name as the class).
- Use libman for all external JS libraries.
- HTML paragraphs (`<p>` element) cannot contain other block-level elements. On the Details page, change the container for the Notes to `<section class="border border-info p-4 rounded mb-3">`. (I included extra formatting to set off the Notes section from the rest of the page.)

As usual, thanks and let me know if you have any questions!

**Review by dougwaldron — APPROVED** [review]

**Pull request merged**
